### ISSUE TITLE
팀이름 지어오기

### ISSUE THREAD

**Issue by dev-jko** [dev-jko/github-repo-chatbot#7]
각자 하나씩 생각해오기

위저드로 정해졌습니다

**Comment by sgh8539** [comment]
재두와 아이들

**Comment by sgh8539** [comment]
재두즈

**Comment by podojuice** [comment]
깃허브에 푸시하면 텔레그램으로 받게 되니까 줄여서 깃푸텔

**Comment by dev-jko** [comment]
notification + 크.. = 노티크

**Comment by yummychuit** [comment]
위저드!!
with재두 로 생각하다 재두님 부담스러우실 것도 같고 나름의 의미를 부여하고자 했습니다!

사전적의미
1 (동화 등에 나오는 남자)마법사
2 귀재
a computer/financial, etc. wizard
컴퓨터/금융 (분야) 등의 귀재
3 (컴퓨터)마법사(다른 프로그램의 실행·작업 등을 도와주는 프로그램)

**Comment by mnoko33** [comment]
깃프로
=Git(flow) + Pro(ject)
겸사겸사 프로가 되고 싶다는 의미도..

**Comment by sgh8539** [comment]
https://movie.hphk.io/movies/ 찡긋

**Comment by dev-jko** [comment]
위저드로 정해졌습니다
